version: '4.24.1'

services:
  backend:
    build:
      context: ./kibolApp
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_HOST: localhost
      DB_DATABASE: kibolAppDB
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - 8000:8000
    volumes:
      - ./kibolApp:/kibolApp
    depends_on:
      - db
    networks:
      - app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
    networks:
      - app

  db:
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kibolAppDB
    ports:
      - "3307:3306"

networks:
  app:
    driver: bridge