version: '4.24.1'

services:
  backend:
    build:
      context: ./kibolapp/app/Backend
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_HOST: sql_server
      DB_DATABASE: kibolAppDB
      DB_USERNAME: ''
      DB_PASSWORD: ''
    ports:
      - 8000:8000
    volumes:
      - ./kibolapp/app/Backend:/kibolapp/app/Backend
    depends_on:
      - sql_server
    networks:
      - app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
    networks:
      - app

  sql_server:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      MSSQL_USER: ""
      MSSQL_PASSWORD: ""
      MSSQL_DATABASE: "kibolAppDB"
    ports:
      - "1433:1433"

networks:
  app:
    driver: bridge
