version: '4.24.1'

services:
  backend:
    build:
      context: ./kibolapp/app/Backend
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_HOST: db
      DB_DATABASE: kibolapp-db-1
      DB_USERNAME: admin
      DB_PASSWORD: admin
    ports:
      - 8000:8000
    volumes:
      - ./kibolapp/app/Backend:/kibolapp/app/Backend
    depends_on:
      - db
    networks:
      - app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
    networks:
      - app

  db:
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kibolapp-db-1
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"

networks:
  app:
    driver: bridge
